import { PROJECTS } from "../data/portfolio";
import { SUPPORTED_LANGS, DEFAULT_LANG, type SupportedLang } from "../i18n";

/**
 * Canonical origin. Every absolute URL in the metadata layer — canonical, hreflang, OG,
 * sitemap — is built from this, so moving domains is a one-line edit.
 */
export const SITE_URL = "https://crowloopstudio.com";

/** Generated by `scripts/generate-og-image.mjs`. PNG rather than WebP: some link-preview
 * scrapers still reject WebP, and this is the one image whose whole job is being scraped. */
export const OG_IMAGE = {
  path: "/brand/og/og-default.png",
  width: 1200,
  height: 630,
} as const;

/** Maps our language codes to the `og:locale` format scrapers expect. */
export const OG_LOCALES: Record<SupportedLang, string> = {
  en: "en_US",
  de: "de_DE",
};

export interface SeoRoute {
  /** Path below the language segment. `""` is the language home page (`/en`, `/de`). */
  path: string;
  /** i18n keys for the title and meta description, namespace-qualified so case-study routes
   * can reuse the project copy that already lives in the `portfolio` namespace. */
  titleKey: string;
  descriptionKey: string;
  /** `<priority>` in sitemap.xml. */
  priority: number;
  /** `og:type` — case studies are articles, everything else is a plain page. */
  ogType: "website" | "article";
}

const staticRoute = (path: string, key: string, priority: number): SeoRoute => ({
  path,
  titleKey: `seo:${key}.title`,
  descriptionKey: `seo:${key}.description`,
  priority,
  ogType: "website",
});

/**
 * Every indexable route, in sitemap order. Case studies are derived from `PROJECTS` rather
 * than listed by hand, so publishing a new case study updates the metadata and the sitemap
 * without touching this file.
 */
export const SEO_ROUTES: SeoRoute[] = [
  staticRoute("", "home", 1.0),
  staticRoute("portfolio", "portfolio", 0.9),
  staticRoute("services", "services", 0.9),
  staticRoute("contact", "contact", 0.9),
  staticRoute("process", "process", 0.8),
  staticRoute("about", "about", 0.8),
  ...PROJECTS.filter((project) => project.isCaseStudy).map(
    (project): SeoRoute => ({
      path: `portfolio/${project.slug}`,
      titleKey: `portfolio:${project.nameKey}`,
      descriptionKey: `portfolio:${project.descriptionKey}`,
      priority: 0.7,
      ogType: "article",
    }),
  ),
  staticRoute("testimonials", "testimonials", 0.5),
  staticRoute("impressum", "impressum", 0.3),
  staticRoute("datenschutz", "datenschutz", 0.3),
  staticRoute("haftungsausschluss", "haftungsausschluss", 0.3),
  staticRoute("agb", "agb", 0.3),
];

/** The 404 route. Not in `SEO_ROUTES` — it is excluded from the sitemap and marked noindex. */
export const NOT_FOUND_ROUTE: SeoRoute = {
  path: "*",
  titleKey: "seo:notFound.title",
  descriptionKey: "seo:notFound.description",
  priority: 0,
  ogType: "website",
};

/** Absolute URL for a route in a given language. Home is `/en`, not `/en/`, matching the
 * links the site itself emits. */
export function urlFor(lang: SupportedLang, path: string): string {
  return path ? `${SITE_URL}/${lang}/${path}` : `${SITE_URL}/${lang}`;
}

/** Strips the language segment off a pathname, returning the route path used by `SEO_ROUTES`. */
export function toRoutePath(pathname: string): string {
  const segments = pathname.replace(/^\/+|\/+$/g, "").split("/");
  return segments.slice(1).join("/");
}

/** Looks up the route for a path below the language segment, or `undefined` when nothing
 * matches — which is exactly the 404 case. */
export function findRoute(routePath: string): SeoRoute | undefined {
  return SEO_ROUTES.find((route) => route.path === routePath);
}

/** Every (language, route) pair — 2 languages x 14 routes. Drives both the sitemap and the
 * prerenderer, so the three can never drift apart. */
export function allRoutePairs(): { lang: SupportedLang; route: SeoRoute }[] {
  return SUPPORTED_LANGS.flatMap((lang) => SEO_ROUTES.map((route) => ({ lang, route })));
}

export { SUPPORTED_LANGS, DEFAULT_LANG };
export type { SupportedLang };
